import "../../src/platform/x11.ab"
import "../../src/driver/opengl.ab"

fun main: int {
    val window = x11Window(WindowConfig(
        title = "Abla OpenGL window",
        width = 800,
        height = 600,
        visible = true
    ))
    val context = openGlWindowContext(window)
    context.makeCurrent()
    val shader = $glsl {
        vertex {
            #version 330 core
            const vec2 p[3] = vec2[3](
                vec2(-1.0, -1.0),
                vec2(3.0, -1.0),
                vec2(-1.0, 3.0)
            );
            void main() {
                gl_Position = vec4(p[gl_VertexID], 0.0, 1.0);
            }
        }
        fragment {
            #version 330 core
            out vec4 color;
            void main() {
                color = vec4(0.1, 0.5, 0.9, 1.0);
            }
        }
    }
    val program = openGlProgramFromPackage(shader)
    val pixel = context.drawAndPresent(program)
    window.pollEvent(750)
    if (pixel >= 0) 0 else 1
}
